### ISSUE TITLE
-file 只能指定url文件，能不能指定ip文件呢

### ISSUE THREAD

**Issue by LuoooB** [zhzyker/dismap#1]

**Comment by zhzyker** [comment]
Mark一下，后续尽量实现

**Comment by LuoooB** [comment]
持续关注！加油



***@***.***
 
发件人： 之乎者也
发送时间： 2021-08-23 15:19
收件人： zhzyker/dismap
抄送： June; Author
主题： Re: [zhzyker/dismap] -file 只能指定url文件，能不能指定ip文件呢 (#1)
Mark一下，后续尽量实现
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shen1in** [comment]
+1 的需求

**Comment by xibeiwangxue** [comment]
也不能写域名吗

**Comment by peilipeili** [comment]
+1  批量扫多个C段经常需要用到

**Comment by zhzyker** [comment]
https://github.com/zhzyker/dismap/releases/v0.2 中完善该功能，允许 ip 域名 网段 url 混合批量识别
