### ISSUE TITLE
Mac m1 运行直接被killed的问题

### ISSUE THREAD

**Issue by hacZhang** [zhzyker/dismap#11]
➜  dismap ./dismap
[1]    19891 killed     ./dismap
➜  dismap ./dismap
[1]    19917 killed     ./dismap
➜  dismap ./dismap
[1]    19925 killed     ./dismap
➜  dismap ll
total 6304
-rwxr-xr-x@ 1  xxxxx  staff   2.8M  3  6 21:46 dismap
➜  dismap

**Comment by Hack3rHan** [comment]
也遇到了这个问题，暂时可以下载最新版本源码，手动go build一下。

**Comment by zhzyker** [comment]
我用arm的mac重新编译了一遍，之前的跨架构编译似乎存在问题
Mac m1 版本信息：
```
00dbd6cb22159bbdaf3cdb23f4561e77  dismap-0.3-darwin-arm64
```
